name: and-env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - pillow
  - matplotlib
  - pyyaml
  - prettytable
  - tensorboardx
  - pytorch=2.4.*
  - torchvision=0.19.*
  - cpuonly
  - pip:
      - faiss-cpu==1.7.4
