name: and-env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - pillow
  - matplotlib
  - pyyaml
  - prettytable
  - tensorboardx
  - pytorch=1.10.2
  - torchvision=0.11.3
  - cpuonly
  - pip:
      - faiss-cpu==1.7.4
